language: python
matrix:
    include:
        - python: "2.6"
          env: ZOOKEEPER_VERSION=3.3.6
        - python: "2.6"
          env: ZOOKEEPER_VERSION=3.4.3
        - python: "2.7"
          env: ZOOKEEPER_VERSION=3.3.6
        - python: "2.7"
          env: ZOOKEEPER_VERSION=3.4.3
        - python: "3.2"
          env: ZOOKEEPER_VERSION=3.3.6
        - python: "3.2"
          env: ZOOKEEPER_VERSION=3.4.3

notifications:
  email:
    - hschlichting@mozilla.com

before_install:
    - sudo apt-get install libevent-dev

install:
    - make
    - make zookeeper

script:
    - make test
