language: python
python:
    - "2.6"
    - "2.7"

notifications:
  email:
    - hschlichting@mozilla.com
    - ben@groovie.org
  irc: "irc.mozilla.org#services-dev"

install:
    - make
    - make zookeeper

script:
    - make test
