language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"

env:
    - ZOOKEEPER_VERSION=3.3.6
    - ZOOKEEPER_VERSION=3.4.3

notifications:
  email:
    - hschlichting@mozilla.com

before_install:
    - sudo apt-get install libevent-dev

install:
    - make
    - make zookeeper

script:
    - make test
